// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using personnel_access_control.DbContexts;

#nullable disable

namespace personnel_access_control.Migrations
{
    [DbContext(typeof(AccessDbContext))]
    [Migration("20230519013615_mockData")]
    partial class mockData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("personnel_access_control.Entities.Access", b =>
                {
                    b.Property<int>("AccessId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AccessId"));

                    b.Property<DateTime>("AccessDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("AccessType")
                        .HasColumnType("int");

                    b.Property<int>("CompanyBranchId")
                        .HasColumnType("int");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.HasKey("AccessId");

                    b.HasIndex("CompanyBranchId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("Accesses");

                    b.HasData(
                        new
                        {
                            AccessId = 30,
                            AccessDateTime = new DateTime(2022, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AccessType = 0,
                            CompanyBranchId = 2,
                            EmployeeId = 1
                        },
                        new
                        {
                            AccessId = 31,
                            AccessDateTime = new DateTime(2022, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AccessType = 1,
                            CompanyBranchId = 1,
                            EmployeeId = 5
                        },
                        new
                        {
                            AccessId = 32,
                            AccessDateTime = new DateTime(2022, 8, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AccessType = 0,
                            CompanyBranchId = 3,
                            EmployeeId = 10
                        },
                        new
                        {
                            AccessId = 33,
                            AccessDateTime = new DateTime(2022, 6, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AccessType = 1,
                            CompanyBranchId = 2,
                            EmployeeId = 3
                        },
                        new
                        {
                            AccessId = 34,
                            AccessDateTime = new DateTime(2022, 7, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AccessType = 0,
                            CompanyBranchId = 1,
                            EmployeeId = 7
                        },
                        new
                        {
                            AccessId = 35,
                            AccessDateTime = new DateTime(2022, 6, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AccessType = 1,
                            CompanyBranchId = 3,
                            EmployeeId = 15
                        },
                        new
                        {
                            AccessId = 36,
                            AccessDateTime = new DateTime(2022, 9, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AccessType = 0,
                            CompanyBranchId = 1,
                            EmployeeId = 12
                        },
                        new
                        {
                            AccessId = 37,
                            AccessDateTime = new DateTime(2022, 2, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AccessType = 1,
                            CompanyBranchId = 2,
                            EmployeeId = 18
                        },
                        new
                        {
                            AccessId = 38,
                            AccessDateTime = new DateTime(2022, 10, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AccessType = 0,
                            CompanyBranchId = 1,
                            EmployeeId = 6
                        },
                        new
                        {
                            AccessId = 39,
                            AccessDateTime = new DateTime(2022, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AccessType = 1,
                            CompanyBranchId = 3,
                            EmployeeId = 9
                        },
                        new
                        {
                            AccessId = 40,
                            AccessDateTime = new DateTime(2022, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AccessType = 1,
                            CompanyBranchId = 3,
                            EmployeeId = 18
                        },
                        new
                        {
                            AccessId = 41,
                            AccessDateTime = new DateTime(2022, 12, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AccessType = 0,
                            CompanyBranchId = 1,
                            EmployeeId = 4
                        },
                        new
                        {
                            AccessId = 42,
                            AccessDateTime = new DateTime(2022, 9, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AccessType = 1,
                            CompanyBranchId = 2,
                            EmployeeId = 15
                        },
                        new
                        {
                            AccessId = 43,
                            AccessDateTime = new DateTime(2022, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AccessType = 0,
                            CompanyBranchId = 1,
                            EmployeeId = 8
                        },
                        new
                        {
                            AccessId = 44,
                            AccessDateTime = new DateTime(2022, 11, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AccessType = 1,
                            CompanyBranchId = 2,
                            EmployeeId = 9
                        },
                        new
                        {
                            AccessId = 45,
                            AccessDateTime = new DateTime(2022, 2, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AccessType = 0,
                            CompanyBranchId = 3,
                            EmployeeId = 13
                        },
                        new
                        {
                            AccessId = 46,
                            AccessDateTime = new DateTime(2022, 1, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AccessType = 1,
                            CompanyBranchId = 2,
                            EmployeeId = 1
                        },
                        new
                        {
                            AccessId = 47,
                            AccessDateTime = new DateTime(2022, 8, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AccessType = 0,
                            CompanyBranchId = 3,
                            EmployeeId = 5
                        },
                        new
                        {
                            AccessId = 48,
                            AccessDateTime = new DateTime(2022, 7, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AccessType = 1,
                            CompanyBranchId = 1,
                            EmployeeId = 10
                        },
                        new
                        {
                            AccessId = 49,
                            AccessDateTime = new DateTime(2022, 3, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AccessType = 0,
                            CompanyBranchId = 2,
                            EmployeeId = 20
                        },
                        new
                        {
                            AccessId = 50,
                            AccessDateTime = new DateTime(2022, 9, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AccessType = 1,
                            CompanyBranchId = 3,
                            EmployeeId = 3
                        },
                        new
                        {
                            AccessId = 51,
                            AccessDateTime = new DateTime(2022, 8, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AccessType = 0,
                            CompanyBranchId = 1,
                            EmployeeId = 17
                        },
                        new
                        {
                            AccessId = 52,
                            AccessDateTime = new DateTime(2022, 3, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AccessType = 1,
                            CompanyBranchId = 2,
                            EmployeeId = 11
                        },
                        new
                        {
                            AccessId = 53,
                            AccessDateTime = new DateTime(2022, 6, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AccessType = 0,
                            CompanyBranchId = 3,
                            EmployeeId = 12
                        },
                        new
                        {
                            AccessId = 54,
                            AccessDateTime = new DateTime(2022, 4, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AccessType = 1,
                            CompanyBranchId = 1,
                            EmployeeId = 16
                        },
                        new
                        {
                            AccessId = 55,
                            AccessDateTime = new DateTime(2022, 11, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AccessType = 0,
                            CompanyBranchId = 2,
                            EmployeeId = 7
                        },
                        new
                        {
                            AccessId = 56,
                            AccessDateTime = new DateTime(2022, 4, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AccessType = 1,
                            CompanyBranchId = 3,
                            EmployeeId = 19
                        },
                        new
                        {
                            AccessId = 57,
                            AccessDateTime = new DateTime(2022, 2, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AccessType = 0,
                            CompanyBranchId = 1,
                            EmployeeId = 6
                        },
                        new
                        {
                            AccessId = 58,
                            AccessDateTime = new DateTime(2022, 10, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AccessType = 1,
                            CompanyBranchId = 2,
                            EmployeeId = 14
                        },
                        new
                        {
                            AccessId = 59,
                            AccessDateTime = new DateTime(2022, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AccessType = 0,
                            CompanyBranchId = 3,
                            EmployeeId = 2
                        },
                        new
                        {
                            AccessId = 60,
                            AccessDateTime = new DateTime(2022, 10, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AccessType = 1,
                            CompanyBranchId = 1,
                            EmployeeId = 8
                        },
                        new
                        {
                            AccessId = 61,
                            AccessDateTime = new DateTime(2022, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AccessType = 0,
                            CompanyBranchId = 2,
                            EmployeeId = 6
                        },
                        new
                        {
                            AccessId = 62,
                            AccessDateTime = new DateTime(2022, 2, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AccessType = 1,
                            CompanyBranchId = 3,
                            EmployeeId = 19
                        },
                        new
                        {
                            AccessId = 63,
                            AccessDateTime = new DateTime(2022, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AccessType = 0,
                            CompanyBranchId = 1,
                            EmployeeId = 13
                        },
                        new
                        {
                            AccessId = 64,
                            AccessDateTime = new DateTime(2022, 9, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AccessType = 1,
                            CompanyBranchId = 2,
                            EmployeeId = 14
                        },
                        new
                        {
                            AccessId = 65,
                            AccessDateTime = new DateTime(2022, 8, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AccessType = 0,
                            CompanyBranchId = 3,
                            EmployeeId = 20
                        },
                        new
                        {
                            AccessId = 66,
                            AccessDateTime = new DateTime(2022, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AccessType = 1,
                            CompanyBranchId = 1,
                            EmployeeId = 8
                        },
                        new
                        {
                            AccessId = 67,
                            AccessDateTime = new DateTime(2022, 11, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AccessType = 0,
                            CompanyBranchId = 2,
                            EmployeeId = 4
                        },
                        new
                        {
                            AccessId = 68,
                            AccessDateTime = new DateTime(2022, 3, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AccessType = 1,
                            CompanyBranchId = 3,
                            EmployeeId = 1
                        },
                        new
                        {
                            AccessId = 69,
                            AccessDateTime = new DateTime(2022, 7, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AccessType = 0,
                            CompanyBranchId = 1,
                            EmployeeId = 10
                        },
                        new
                        {
                            AccessId = 70,
                            AccessDateTime = new DateTime(2022, 2, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AccessType = 1,
                            CompanyBranchId = 2,
                            EmployeeId = 5
                        },
                        new
                        {
                            AccessId = 71,
                            AccessDateTime = new DateTime(2022, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AccessType = 0,
                            CompanyBranchId = 3,
                            EmployeeId = 11
                        },
                        new
                        {
                            AccessId = 72,
                            AccessDateTime = new DateTime(2022, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AccessType = 1,
                            CompanyBranchId = 1,
                            EmployeeId = 17
                        },
                        new
                        {
                            AccessId = 73,
                            AccessDateTime = new DateTime(2022, 10, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AccessType = 0,
                            CompanyBranchId = 2,
                            EmployeeId = 15
                        },
                        new
                        {
                            AccessId = 74,
                            AccessDateTime = new DateTime(2022, 9, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AccessType = 1,
                            CompanyBranchId = 3,
                            EmployeeId = 12
                        },
                        new
                        {
                            AccessId = 75,
                            AccessDateTime = new DateTime(2022, 6, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AccessType = 0,
                            CompanyBranchId = 1,
                            EmployeeId = 7
                        },
                        new
                        {
                            AccessId = 76,
                            AccessDateTime = new DateTime(2022, 11, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AccessType = 1,
                            CompanyBranchId = 2,
                            EmployeeId = 9
                        },
                        new
                        {
                            AccessId = 77,
                            AccessDateTime = new DateTime(2022, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AccessType = 0,
                            CompanyBranchId = 3,
                            EmployeeId = 16
                        },
                        new
                        {
                            AccessId = 78,
                            AccessDateTime = new DateTime(2022, 12, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AccessType = 1,
                            CompanyBranchId = 1,
                            EmployeeId = 3
                        },
                        new
                        {
                            AccessId = 79,
                            AccessDateTime = new DateTime(2022, 5, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AccessType = 0,
                            CompanyBranchId = 2,
                            EmployeeId = 18
                        },
                        new
                        {
                            AccessId = 80,
                            AccessDateTime = new DateTime(2022, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AccessType = 1,
                            CompanyBranchId = 3,
                            EmployeeId = 2
                        },
                        new
                        {
                            AccessId = 81,
                            AccessDateTime = new DateTime(2022, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AccessType = 0,
                            CompanyBranchId = 1,
                            EmployeeId = 12
                        },
                        new
                        {
                            AccessId = 82,
                            AccessDateTime = new DateTime(2022, 2, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AccessType = 0,
                            CompanyBranchId = 3,
                            EmployeeId = 19
                        },
                        new
                        {
                            AccessId = 83,
                            AccessDateTime = new DateTime(2022, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AccessType = 1,
                            CompanyBranchId = 2,
                            EmployeeId = 5
                        },
                        new
                        {
                            AccessId = 84,
                            AccessDateTime = new DateTime(2022, 8, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AccessType = 0,
                            CompanyBranchId = 1,
                            EmployeeId = 11
                        },
                        new
                        {
                            AccessId = 85,
                            AccessDateTime = new DateTime(2022, 7, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AccessType = 1,
                            CompanyBranchId = 2,
                            EmployeeId = 17
                        },
                        new
                        {
                            AccessId = 86,
                            AccessDateTime = new DateTime(2022, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AccessType = 1,
                            CompanyBranchId = 3,
                            EmployeeId = 6
                        },
                        new
                        {
                            AccessId = 87,
                            AccessDateTime = new DateTime(2022, 11, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AccessType = 0,
                            CompanyBranchId = 1,
                            EmployeeId = 3
                        },
                        new
                        {
                            AccessId = 88,
                            AccessDateTime = new DateTime(2022, 4, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AccessType = 1,
                            CompanyBranchId = 3,
                            EmployeeId = 9
                        },
                        new
                        {
                            AccessId = 89,
                            AccessDateTime = new DateTime(2022, 7, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AccessType = 0,
                            CompanyBranchId = 1,
                            EmployeeId = 20
                        },
                        new
                        {
                            AccessId = 90,
                            AccessDateTime = new DateTime(2022, 3, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AccessType = 1,
                            CompanyBranchId = 2,
                            EmployeeId = 14
                        },
                        new
                        {
                            AccessId = 91,
                            AccessDateTime = new DateTime(2022, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AccessType = 0,
                            CompanyBranchId = 3,
                            EmployeeId = 18
                        },
                        new
                        {
                            AccessId = 92,
                            AccessDateTime = new DateTime(2022, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AccessType = 0,
                            CompanyBranchId = 1,
                            EmployeeId = 4
                        },
                        new
                        {
                            AccessId = 93,
                            AccessDateTime = new DateTime(2022, 11, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AccessType = 1,
                            CompanyBranchId = 2,
                            EmployeeId = 7
                        },
                        new
                        {
                            AccessId = 94,
                            AccessDateTime = new DateTime(2022, 10, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AccessType = 1,
                            CompanyBranchId = 3,
                            EmployeeId = 16
                        },
                        new
                        {
                            AccessId = 95,
                            AccessDateTime = new DateTime(2022, 2, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AccessType = 0,
                            CompanyBranchId = 1,
                            EmployeeId = 2
                        },
                        new
                        {
                            AccessId = 96,
                            AccessDateTime = new DateTime(2022, 12, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AccessType = 0,
                            CompanyBranchId = 2,
                            EmployeeId = 10
                        },
                        new
                        {
                            AccessId = 97,
                            AccessDateTime = new DateTime(2022, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AccessType = 1,
                            CompanyBranchId = 1,
                            EmployeeId = 15
                        },
                        new
                        {
                            AccessId = 98,
                            AccessDateTime = new DateTime(2022, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AccessType = 0,
                            CompanyBranchId = 3,
                            EmployeeId = 8
                        },
                        new
                        {
                            AccessId = 99,
                            AccessDateTime = new DateTime(2022, 9, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AccessType = 1,
                            CompanyBranchId = 1,
                            EmployeeId = 13
                        },
                        new
                        {
                            AccessId = 100,
                            AccessDateTime = new DateTime(2022, 8, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AccessType = 1,
                            CompanyBranchId = 2,
                            EmployeeId = 19
                        },
                        new
                        {
                            AccessId = 101,
                            AccessDateTime = new DateTime(2022, 7, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AccessType = 0,
                            CompanyBranchId = 1,
                            EmployeeId = 14
                        },
                        new
                        {
                            AccessId = 102,
                            AccessDateTime = new DateTime(2022, 1, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AccessType = 1,
                            CompanyBranchId = 2,
                            EmployeeId = 20
                        },
                        new
                        {
                            AccessId = 103,
                            AccessDateTime = new DateTime(2022, 11, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AccessType = 1,
                            CompanyBranchId = 3,
                            EmployeeId = 6
                        },
                        new
                        {
                            AccessId = 104,
                            AccessDateTime = new DateTime(2022, 8, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AccessType = 0,
                            CompanyBranchId = 1,
                            EmployeeId = 10
                        },
                        new
                        {
                            AccessId = 105,
                            AccessDateTime = new DateTime(2022, 6, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AccessType = 0,
                            CompanyBranchId = 2,
                            EmployeeId = 17
                        },
                        new
                        {
                            AccessId = 106,
                            AccessDateTime = new DateTime(2022, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AccessType = 0,
                            CompanyBranchId = 3,
                            EmployeeId = 5
                        },
                        new
                        {
                            AccessId = 107,
                            AccessDateTime = new DateTime(2022, 10, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AccessType = 1,
                            CompanyBranchId = 1,
                            EmployeeId = 1
                        },
                        new
                        {
                            AccessId = 108,
                            AccessDateTime = new DateTime(2022, 4, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AccessType = 1,
                            CompanyBranchId = 3,
                            EmployeeId = 19
                        },
                        new
                        {
                            AccessId = 109,
                            AccessDateTime = new DateTime(2022, 7, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AccessType = 0,
                            CompanyBranchId = 1,
                            EmployeeId = 2
                        },
                        new
                        {
                            AccessId = 110,
                            AccessDateTime = new DateTime(2022, 3, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AccessType = 1,
                            CompanyBranchId = 2,
                            EmployeeId = 16
                        },
                        new
                        {
                            AccessId = 111,
                            AccessDateTime = new DateTime(2022, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AccessType = 0,
                            CompanyBranchId = 3,
                            EmployeeId = 18
                        },
                        new
                        {
                            AccessId = 112,
                            AccessDateTime = new DateTime(2022, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AccessType = 0,
                            CompanyBranchId = 1,
                            EmployeeId = 3
                        },
                        new
                        {
                            AccessId = 113,
                            AccessDateTime = new DateTime(2022, 11, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AccessType = 1,
                            CompanyBranchId = 2,
                            EmployeeId = 7
                        },
                        new
                        {
                            AccessId = 114,
                            AccessDateTime = new DateTime(2022, 10, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AccessType = 0,
                            CompanyBranchId = 3,
                            EmployeeId = 16
                        },
                        new
                        {
                            AccessId = 115,
                            AccessDateTime = new DateTime(2022, 3, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AccessType = 1,
                            CompanyBranchId = 1,
                            EmployeeId = 12
                        },
                        new
                        {
                            AccessId = 116,
                            AccessDateTime = new DateTime(2022, 9, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AccessType = 0,
                            CompanyBranchId = 2,
                            EmployeeId = 9
                        },
                        new
                        {
                            AccessId = 117,
                            AccessDateTime = new DateTime(2022, 7, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AccessType = 1,
                            CompanyBranchId = 3,
                            EmployeeId = 13
                        },
                        new
                        {
                            AccessId = 118,
                            AccessDateTime = new DateTime(2022, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AccessType = 0,
                            CompanyBranchId = 1,
                            EmployeeId = 4
                        },
                        new
                        {
                            AccessId = 119,
                            AccessDateTime = new DateTime(2022, 2, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AccessType = 1,
                            CompanyBranchId = 2,
                            EmployeeId = 11
                        },
                        new
                        {
                            AccessId = 120,
                            AccessDateTime = new DateTime(2022, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AccessType = 1,
                            CompanyBranchId = 3,
                            EmployeeId = 8
                        },
                        new
                        {
                            AccessId = 121,
                            AccessDateTime = new DateTime(2022, 9, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AccessType = 0,
                            CompanyBranchId = 1,
                            EmployeeId = 15
                        },
                        new
                        {
                            AccessId = 122,
                            AccessDateTime = new DateTime(2022, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AccessType = 1,
                            CompanyBranchId = 2,
                            EmployeeId = 2
                        },
                        new
                        {
                            AccessId = 123,
                            AccessDateTime = new DateTime(2022, 8, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AccessType = 0,
                            CompanyBranchId = 3,
                            EmployeeId = 5
                        },
                        new
                        {
                            AccessId = 124,
                            AccessDateTime = new DateTime(2022, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AccessType = 1,
                            CompanyBranchId = 1,
                            EmployeeId = 8
                        },
                        new
                        {
                            AccessId = 125,
                            AccessDateTime = new DateTime(2022, 5, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AccessType = 0,
                            CompanyBranchId = 2,
                            EmployeeId = 19
                        },
                        new
                        {
                            AccessId = 126,
                            AccessDateTime = new DateTime(2022, 12, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AccessType = 0,
                            CompanyBranchId = 3,
                            EmployeeId = 10
                        },
                        new
                        {
                            AccessId = 127,
                            AccessDateTime = new DateTime(2022, 11, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AccessType = 1,
                            CompanyBranchId = 1,
                            EmployeeId = 12
                        },
                        new
                        {
                            AccessId = 128,
                            AccessDateTime = new DateTime(2022, 5, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AccessType = 1,
                            CompanyBranchId = 3,
                            EmployeeId = 16
                        },
                        new
                        {
                            AccessId = 129,
                            AccessDateTime = new DateTime(2022, 9, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AccessType = 0,
                            CompanyBranchId = 1,
                            EmployeeId = 1
                        },
                        new
                        {
                            AccessId = 130,
                            AccessDateTime = new DateTime(2022, 4, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AccessType = 1,
                            CompanyBranchId = 2,
                            EmployeeId = 18
                        },
                        new
                        {
                            AccessId = 131,
                            AccessDateTime = new DateTime(2022, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AccessType = 0,
                            CompanyBranchId = 3,
                            EmployeeId = 20
                        },
                        new
                        {
                            AccessId = 132,
                            AccessDateTime = new DateTime(2022, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AccessType = 0,
                            CompanyBranchId = 1,
                            EmployeeId = 3
                        },
                        new
                        {
                            AccessId = 133,
                            AccessDateTime = new DateTime(2022, 12, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AccessType = 1,
                            CompanyBranchId = 2,
                            EmployeeId = 6
                        },
                        new
                        {
                            AccessId = 134,
                            AccessDateTime = new DateTime(2022, 11, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AccessType = 0,
                            CompanyBranchId = 3,
                            EmployeeId = 16
                        },
                        new
                        {
                            AccessId = 135,
                            AccessDateTime = new DateTime(2022, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AccessType = 1,
                            CompanyBranchId = 1,
                            EmployeeId = 7
                        },
                        new
                        {
                            AccessId = 136,
                            AccessDateTime = new DateTime(2022, 7, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AccessType = 0,
                            CompanyBranchId = 2,
                            EmployeeId = 14
                        },
                        new
                        {
                            AccessId = 137,
                            AccessDateTime = new DateTime(2022, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AccessType = 0,
                            CompanyBranchId = 3,
                            EmployeeId = 4
                        },
                        new
                        {
                            AccessId = 138,
                            AccessDateTime = new DateTime(2022, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AccessType = 1,
                            CompanyBranchId = 1,
                            EmployeeId = 17
                        },
                        new
                        {
                            AccessId = 139,
                            AccessDateTime = new DateTime(2022, 1, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AccessType = 0,
                            CompanyBranchId = 2,
                            EmployeeId = 9
                        },
                        new
                        {
                            AccessId = 140,
                            AccessDateTime = new DateTime(2022, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AccessType = 1,
                            CompanyBranchId = 3,
                            EmployeeId = 13
                        },
                        new
                        {
                            AccessId = 141,
                            AccessDateTime = new DateTime(2022, 10, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AccessType = 0,
                            CompanyBranchId = 1,
                            EmployeeId = 5
                        },
                        new
                        {
                            AccessId = 142,
                            AccessDateTime = new DateTime(2022, 2, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AccessType = 1,
                            CompanyBranchId = 2,
                            EmployeeId = 17
                        },
                        new
                        {
                            AccessId = 143,
                            AccessDateTime = new DateTime(2022, 12, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AccessType = 0,
                            CompanyBranchId = 3,
                            EmployeeId = 9
                        },
                        new
                        {
                            AccessId = 144,
                            AccessDateTime = new DateTime(2022, 8, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AccessType = 1,
                            CompanyBranchId = 1,
                            EmployeeId = 3
                        },
                        new
                        {
                            AccessId = 145,
                            AccessDateTime = new DateTime(2022, 4, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AccessType = 0,
                            CompanyBranchId = 2,
                            EmployeeId = 16
                        },
                        new
                        {
                            AccessId = 146,
                            AccessDateTime = new DateTime(2022, 11, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AccessType = 0,
                            CompanyBranchId = 3,
                            EmployeeId = 8
                        },
                        new
                        {
                            AccessId = 147,
                            AccessDateTime = new DateTime(2022, 1, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AccessType = 1,
                            CompanyBranchId = 1,
                            EmployeeId = 12
                        },
                        new
                        {
                            AccessId = 148,
                            AccessDateTime = new DateTime(2022, 5, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AccessType = 1,
                            CompanyBranchId = 3,
                            EmployeeId = 1
                        },
                        new
                        {
                            AccessId = 149,
                            AccessDateTime = new DateTime(2022, 9, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AccessType = 0,
                            CompanyBranchId = 1,
                            EmployeeId = 19
                        },
                        new
                        {
                            AccessId = 150,
                            AccessDateTime = new DateTime(2022, 5, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AccessType = 1,
                            CompanyBranchId = 2,
                            EmployeeId = 18
                        },
                        new
                        {
                            AccessId = 151,
                            AccessDateTime = new DateTime(2022, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AccessType = 0,
                            CompanyBranchId = 3,
                            EmployeeId = 20
                        },
                        new
                        {
                            AccessId = 152,
                            AccessDateTime = new DateTime(2022, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AccessType = 0,
                            CompanyBranchId = 1,
                            EmployeeId = 2
                        },
                        new
                        {
                            AccessId = 153,
                            AccessDateTime = new DateTime(2022, 11, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AccessType = 1,
                            CompanyBranchId = 2,
                            EmployeeId = 6
                        },
                        new
                        {
                            AccessId = 154,
                            AccessDateTime = new DateTime(2022, 11, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AccessType = 0,
                            CompanyBranchId = 3,
                            EmployeeId = 16
                        },
                        new
                        {
                            AccessId = 155,
                            AccessDateTime = new DateTime(2022, 7, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AccessType = 1,
                            CompanyBranchId = 1,
                            EmployeeId = 13
                        },
                        new
                        {
                            AccessId = 156,
                            AccessDateTime = new DateTime(2022, 3, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AccessType = 0,
                            CompanyBranchId = 2,
                            EmployeeId = 15
                        },
                        new
                        {
                            AccessId = 157,
                            AccessDateTime = new DateTime(2022, 12, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AccessType = 0,
                            CompanyBranchId = 3,
                            EmployeeId = 11
                        },
                        new
                        {
                            AccessId = 158,
                            AccessDateTime = new DateTime(2022, 2, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AccessType = 1,
                            CompanyBranchId = 1,
                            EmployeeId = 10
                        },
                        new
                        {
                            AccessId = 159,
                            AccessDateTime = new DateTime(2022, 6, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AccessType = 1,
                            CompanyBranchId = 3,
                            EmployeeId = 7
                        },
                        new
                        {
                            AccessId = 160,
                            AccessDateTime = new DateTime(2022, 10, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AccessType = 0,
                            CompanyBranchId = 1,
                            EmployeeId = 9
                        },
                        new
                        {
                            AccessId = 161,
                            AccessDateTime = new DateTime(2022, 6, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AccessType = 1,
                            CompanyBranchId = 2,
                            EmployeeId = 5
                        },
                        new
                        {
                            AccessId = 181,
                            AccessDateTime = new DateTime(2022, 7, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AccessType = 0,
                            CompanyBranchId = 1,
                            EmployeeId = 6
                        },
                        new
                        {
                            AccessId = 182,
                            AccessDateTime = new DateTime(2022, 1, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AccessType = 1,
                            CompanyBranchId = 2,
                            EmployeeId = 9
                        },
                        new
                        {
                            AccessId = 183,
                            AccessDateTime = new DateTime(2022, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AccessType = 0,
                            CompanyBranchId = 3,
                            EmployeeId = 17
                        },
                        new
                        {
                            AccessId = 184,
                            AccessDateTime = new DateTime(2022, 6, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AccessType = 1,
                            CompanyBranchId = 1,
                            EmployeeId = 13
                        },
                        new
                        {
                            AccessId = 185,
                            AccessDateTime = new DateTime(2022, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AccessType = 0,
                            CompanyBranchId = 2,
                            EmployeeId = 19
                        },
                        new
                        {
                            AccessId = 186,
                            AccessDateTime = new DateTime(2022, 8, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AccessType = 0,
                            CompanyBranchId = 3,
                            EmployeeId = 15
                        },
                        new
                        {
                            AccessId = 187,
                            AccessDateTime = new DateTime(2022, 2, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AccessType = 1,
                            CompanyBranchId = 1,
                            EmployeeId = 10
                        },
                        new
                        {
                            AccessId = 188,
                            AccessDateTime = new DateTime(2022, 4, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AccessType = 1,
                            CompanyBranchId = 3,
                            EmployeeId = 4
                        },
                        new
                        {
                            AccessId = 189,
                            AccessDateTime = new DateTime(2022, 9, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AccessType = 0,
                            CompanyBranchId = 1,
                            EmployeeId = 8
                        },
                        new
                        {
                            AccessId = 190,
                            AccessDateTime = new DateTime(2022, 5, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AccessType = 1,
                            CompanyBranchId = 2,
                            EmployeeId = 18
                        },
                        new
                        {
                            AccessId = 191,
                            AccessDateTime = new DateTime(2022, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AccessType = 0,
                            CompanyBranchId = 3,
                            EmployeeId = 14
                        },
                        new
                        {
                            AccessId = 192,
                            AccessDateTime = new DateTime(2022, 3, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AccessType = 0,
                            CompanyBranchId = 1,
                            EmployeeId = 2
                        },
                        new
                        {
                            AccessId = 193,
                            AccessDateTime = new DateTime(2022, 11, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AccessType = 1,
                            CompanyBranchId = 2,
                            EmployeeId = 7
                        },
                        new
                        {
                            AccessId = 194,
                            AccessDateTime = new DateTime(2022, 11, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AccessType = 0,
                            CompanyBranchId = 3,
                            EmployeeId = 16
                        },
                        new
                        {
                            AccessId = 195,
                            AccessDateTime = new DateTime(2022, 2, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AccessType = 1,
                            CompanyBranchId = 1,
                            EmployeeId = 12
                        },
                        new
                        {
                            AccessId = 196,
                            AccessDateTime = new DateTime(2022, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AccessType = 1,
                            CompanyBranchId = 3,
                            EmployeeId = 20
                        },
                        new
                        {
                            AccessId = 197,
                            AccessDateTime = new DateTime(2022, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AccessType = 0,
                            CompanyBranchId = 1,
                            EmployeeId = 3
                        },
                        new
                        {
                            AccessId = 198,
                            AccessDateTime = new DateTime(2022, 1, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AccessType = 1,
                            CompanyBranchId = 2,
                            EmployeeId = 6
                        },
                        new
                        {
                            AccessId = 199,
                            AccessDateTime = new DateTime(2022, 9, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AccessType = 0,
                            CompanyBranchId = 3,
                            EmployeeId = 17
                        },
                        new
                        {
                            AccessId = 200,
                            AccessDateTime = new DateTime(2022, 7, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AccessType = 1,
                            CompanyBranchId = 1,
                            EmployeeId = 13
                        });
                });

            modelBuilder.Entity("personnel_access_control.Entities.CompanyBranch", b =>
                {
                    b.Property<int>("CompanyBranchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CompanyBranchId"));

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CompanyBranchId");

                    b.ToTable("CompanyBranches");

                    b.HasData(
                        new
                        {
                            CompanyBranchId = 1,
                            Location = "Argentina"
                        },
                        new
                        {
                            CompanyBranchId = 2,
                            Location = "Brasil"
                        },
                        new
                        {
                            CompanyBranchId = 3,
                            Location = "España"
                        });
                });

            modelBuilder.Entity("personnel_access_control.Entities.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeId"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EmployeeId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            EmployeeId = 1,
                            FirstName = "Lucas",
                            Gender = 0,
                            LastName = "Rodriguez"
                        },
                        new
                        {
                            EmployeeId = 2,
                            FirstName = "Delfina",
                            Gender = 1,
                            LastName = "Torres"
                        },
                        new
                        {
                            EmployeeId = 3,
                            FirstName = "Bianca",
                            Gender = 1,
                            LastName = "Perez"
                        },
                        new
                        {
                            EmployeeId = 4,
                            FirstName = "Juan",
                            Gender = 0,
                            LastName = "Gonzalez"
                        },
                        new
                        {
                            EmployeeId = 5,
                            FirstName = "Sofia",
                            Gender = 1,
                            LastName = "Lopez"
                        },
                        new
                        {
                            EmployeeId = 6,
                            FirstName = "Diego",
                            Gender = 0,
                            LastName = "Fernandez"
                        },
                        new
                        {
                            EmployeeId = 7,
                            FirstName = "Valentina",
                            Gender = 1,
                            LastName = "Silva"
                        },
                        new
                        {
                            EmployeeId = 8,
                            FirstName = "Mateo",
                            Gender = 0,
                            LastName = "Hernandez"
                        },
                        new
                        {
                            EmployeeId = 9,
                            FirstName = "Isabella",
                            Gender = 1,
                            LastName = "Gomez"
                        },
                        new
                        {
                            EmployeeId = 10,
                            FirstName = "Martin",
                            Gender = 0,
                            LastName = "Pereira"
                        },
                        new
                        {
                            EmployeeId = 11,
                            FirstName = "Camila",
                            Gender = 1,
                            LastName = "Rojas"
                        },
                        new
                        {
                            EmployeeId = 12,
                            FirstName = "Joaquin",
                            Gender = 0,
                            LastName = "Luna"
                        },
                        new
                        {
                            EmployeeId = 13,
                            FirstName = "Mia",
                            Gender = 1,
                            LastName = "Fuentes"
                        },
                        new
                        {
                            EmployeeId = 14,
                            FirstName = "Facundo",
                            Gender = 0,
                            LastName = "Mendoza"
                        },
                        new
                        {
                            EmployeeId = 15,
                            FirstName = "Valeria",
                            Gender = 1,
                            LastName = "Castillo"
                        },
                        new
                        {
                            EmployeeId = 16,
                            FirstName = "Ignacio",
                            Gender = 0,
                            LastName = "Navarro"
                        },
                        new
                        {
                            EmployeeId = 17,
                            FirstName = "Luz",
                            Gender = 1,
                            LastName = "Santos"
                        },
                        new
                        {
                            EmployeeId = 18,
                            FirstName = "Emilio",
                            Gender = 0,
                            LastName = "Paz"
                        },
                        new
                        {
                            EmployeeId = 19,
                            FirstName = "Catalina",
                            Gender = 1,
                            LastName = "Cardenas"
                        },
                        new
                        {
                            EmployeeId = 20,
                            FirstName = "Sebastian",
                            Gender = 0,
                            LastName = "Ramos"
                        });
                });

            modelBuilder.Entity("personnel_access_control.Entities.Access", b =>
                {
                    b.HasOne("personnel_access_control.Entities.CompanyBranch", "CompanyBranch")
                        .WithMany()
                        .HasForeignKey("CompanyBranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("personnel_access_control.Entities.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CompanyBranch");

                    b.Navigation("Employee");
                });
#pragma warning restore 612, 618
        }
    }
}
